import type { CanvasDocument } from "@/editor/types";

export const EDITOR_TEMPLATES: CanvasDocument[] = [
  {
    id: "studio-square",
    name: "工作室手记",
    description: "方形社交海报",
    width: 1080,
    height: 1080,
    elements: [
      {
        id: "square-background",
        type: "rect",
        name: "暖灰背景",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        fill: "#e8e1d8",
        cornerRadius: 0,
      },
      {
        id: "square-photo-group",
        type: "group",
        name: "主视觉",
        visible: true,
        locked: false,
        children: [
          {
            id: "square-photo",
            type: "image",
            name: "工作室照片",
            x: 86,
            y: 82,
            width: 908,
            height: 606,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            src: "/templates/studio.svg",
            fit: "cover",
            cornerRadius: 28,
          },
          {
            id: "square-badge",
            type: "circle",
            name: "期号徽章",
            x: 852,
            y: 52,
            width: 156,
            height: 156,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            fill: "#ef6b43",
          },
          {
            id: "square-badge-text",
            type: "text",
            name: "徽章文字",
            x: 866,
            y: 101,
            width: 128,
            height: 60,
            rotation: 8,
            opacity: 1,
            visible: true,
            locked: false,
            text: "第 04 期",
            fontSize: 28,
            fontWeight: "700",
            align: "center",
            fill: "#fffaf2",
          },
        ],
      },
      {
        id: "square-copy-group",
        type: "group",
        name: "文案",
        visible: true,
        locked: false,
        children: [
          {
            id: "square-kicker",
            type: "text",
            name: "栏目",
            x: 86,
            y: 746,
            width: 310,
            height: 42,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            text: "物件 / 人物 / 场所",
            fontSize: 22,
            fontWeight: "700",
            align: "left",
            fill: "#ef6b43",
          },
          {
            id: "square-title",
            type: "text",
            name: "主标题",
            x: 82,
            y: 802,
            width: 750,
            height: 148,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            text: "安静地\n创造",
            fontSize: 67,
            fontWeight: "800",
            align: "left",
            fill: "#1f3f36",
          },
          {
            id: "square-index",
            type: "text",
            name: "索引",
            x: 866,
            y: 835,
            width: 128,
            height: 90,
            rotation: 0,
            opacity: 0.75,
            visible: true,
            locked: false,
            text: "2024-2025\n上海",
            fontSize: 21,
            fontWeight: "600",
            align: "right",
            fill: "#1f3f36",
          },
        ],
      },
    ],
  },
  {
    id: "field-landscape",
    name: "旷野笔记",
    description: "横版品牌封面",
    width: 1600,
    height: 900,
    elements: [
      {
        id: "landscape-background",
        type: "rect",
        name: "深绿背景",
        x: 0,
        y: 0,
        width: 1600,
        height: 900,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        fill: "#173f35",
        cornerRadius: 0,
      },
      {
        id: "landscape-image",
        type: "image",
        name: "自然图像",
        x: 790,
        y: 54,
        width: 756,
        height: 792,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        src: "/templates/field.svg",
        fit: "cover",
        cornerRadius: 34,
      },
      {
        id: "landscape-copy-group",
        type: "group",
        name: "品牌文案",
        visible: true,
        locked: false,
        children: [
          {
            id: "landscape-label",
            type: "text",
            name: "标签",
            x: 72,
            y: 76,
            width: 330,
            height: 42,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            text: "旷野笔记 · 2026",
            fontSize: 24,
            fontWeight: "700",
            align: "left",
            fill: "#e7e1d3",
          },
          {
            id: "landscape-title",
            type: "text",
            name: "主标题",
            x: 68,
            y: 252,
            width: 680,
            height: 240,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            text: "为旷野\n留出空间",
            fontSize: 88,
            fontWeight: "800",
            align: "left",
            fill: "#f5f0e6",
          },
          {
            id: "landscape-rule",
            type: "rect",
            name: "强调线",
            x: 72,
            y: 560,
            width: 158,
            height: 10,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            fill: "#e0ac4f",
            cornerRadius: 5,
          },
          {
            id: "landscape-body",
            type: "text",
            name: "说明文字",
            x: 72,
            y: 620,
            width: 570,
            height: 100,
            rotation: 0,
            opacity: 0.82,
            visible: true,
            locked: false,
            text: "记录缓慢的日常、开阔的天空，\n以及专注而有意识的工作。",
            fontSize: 29,
            fontWeight: "400",
            align: "left",
            fill: "#f5f0e6",
          },
        ],
      },
    ],
  },
  {
    id: "editorial-portrait",
    name: "生活新章",
    description: "竖版编辑海报",
    width: 1080,
    height: 1350,
    elements: [
      {
        id: "portrait-background",
        type: "rect",
        name: "纸张背景",
        x: 0,
        y: 0,
        width: 1080,
        height: 1350,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        fill: "#f1eee5",
        cornerRadius: 0,
      },
      {
        id: "portrait-header-group",
        type: "group",
        name: "刊头",
        visible: true,
        locked: false,
        children: [
          {
            id: "portrait-issue",
            type: "text",
            name: "期号",
            x: 70,
            y: 60,
            width: 230,
            height: 48,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            text: "生活志 / 08",
            fontSize: 24,
            fontWeight: "700",
            align: "left",
            fill: "#22211f",
          },
          {
            id: "portrait-mark",
            type: "circle",
            name: "标记",
            x: 908,
            y: 52,
            width: 96,
            height: 96,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            fill: "#cf4b33",
          },
        ],
      },
      {
        id: "portrait-title",
        type: "text",
        name: "主标题",
        x: 64,
        y: 172,
        width: 920,
        height: 212,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        text: "日常生活的\n新仪式",
        fontSize: 90,
        fontWeight: "800",
        align: "left",
        fill: "#22211f",
      },
      {
        id: "portrait-image",
        type: "image",
        name: "静物图像",
        x: 66,
        y: 440,
        width: 948,
        height: 650,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        src: "/templates/ritual.svg",
        fit: "cover",
        cornerRadius: 20,
      },
      {
        id: "portrait-footer-group",
        type: "group",
        name: "页脚信息",
        visible: true,
        locked: false,
        children: [
          {
            id: "portrait-caption",
            type: "text",
            name: "说明",
            x: 68,
            y: 1142,
            width: 575,
            height: 96,
            rotation: 0,
            opacity: 0.78,
            visible: true,
            locked: false,
            text: "细微的行动，塑造着我们\n每天回到的空间。",
            fontSize: 28,
            fontWeight: "500",
            align: "left",
            fill: "#22211f",
          },
          {
            id: "portrait-meta",
            type: "text",
            name: "日期",
            x: 720,
            y: 1150,
            width: 294,
            height: 76,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            text: "七月 - 九月\n上海",
            fontSize: 24,
            fontWeight: "700",
            align: "right",
            fill: "#cf4b33",
          },
        ],
      },
    ],
  },
];
